# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base_Interfaz_Usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1654, 954)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contenedor = QtWidgets.QWidget(Form)
        self.Contenedor.setStyleSheet("\n"
"QPushButton, QToolButton {\n"
"    border-radius: 15px;\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: left; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"     color: black;               /* Color del texto */\n"
"    border: 1px solid transparent;\n"
"    padding-left: 10px;         /* Espaciado entre el ícono y el borde izquierdo */\n"
"    padding-right: 10px;        /* Espaciado entre el ícono y el borde derecho */\n"
"    padding-top: 5px;           /* Espaciado vertical */\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"         background-color: #f2f2f2; /* Gris claro al pasar el mouse */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"    border: none; /* Sin bordes visibles */\n"
"    padding: 4px; /* Espaciado interno entre el texto y los bordes */\n"
"    margin-right: 40px; /* Espaciado externo solo a la derecha */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    color: black; /* Texto negro */\n"
"    text-align: left; /* Texto alineado a la izquierda */\n"
"    font-size: 18px; /* Tamaño del texto */\n"
"}\n"
"\n"
"/* Cuando el QLineEdit está enfocado (se está escribiendo) */\n"
"QLineEdit:focus {\n"
"    background-color: rgb(230, 230, 250); /* Color de fondo cuando el campo está activo */\n"
"    border: 1px solid rgb(0, 0, 0); /* Borde negro al estar activo */\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    color:  black; /* Color del texto */\n"
"    margin-right: 10px; /* Espaciado a la derecha */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    text-align: left; /* Alineación del texto a la izquierda */\n"
"}\n"
"\n"
"")
        self.Contenedor.setObjectName("Contenedor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenedor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.navbar = QtWidgets.QWidget(self.Contenedor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navbar.sizePolicy().hasHeightForWidth())
        self.navbar.setSizePolicy(sizePolicy)
        self.navbar.setMinimumSize(QtCore.QSize(250, 0))
        self.navbar.setStyleSheet("#navbar {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border-right: 1px solid black; /* Borde negro en el lado derecho */\n"
"}\n"
"")
        self.navbar.setObjectName("navbar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.navbar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelImg = QtWidgets.QLabel(self.navbar)
        self.LabelImg.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.LabelImg.sizePolicy().hasHeightForWidth())
        self.LabelImg.setSizePolicy(sizePolicy)
        self.LabelImg.setMinimumSize(QtCore.QSize(100, 50))
        self.LabelImg.setMaximumSize(QtCore.QSize(260, 70))
        self.LabelImg.setStyleSheet("#LabelImg {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: 100% 100%; /* Ajusta la imagen para que ocupe todo el área del label */\n"
"    height: 200px; /* Ajusta la altura del QLabel */\n"
"    width: 300px; /* Ajusta el ancho del QLabel */\n"
"}\n"
"")
        self.LabelImg.setText("")
        self.LabelImg.setPixmap(QtGui.QPixmap("../../assets/Letras-sinfondo.png"))
        self.LabelImg.setScaledContents(True)
        self.LabelImg.setObjectName("LabelImg")
        self.verticalLayout.addWidget(self.LabelImg)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.LabelFuncionalidades = QtWidgets.QLabel(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelFuncionalidades.sizePolicy().hasHeightForWidth())
        self.LabelFuncionalidades.setSizePolicy(sizePolicy)
        self.LabelFuncionalidades.setMinimumSize(QtCore.QSize(250, 30))
        self.LabelFuncionalidades.setMaximumSize(QtCore.QSize(300, 50))
        self.LabelFuncionalidades.setStyleSheet("#LabelFuncionalidades {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelFuncionalidades.setObjectName("LabelFuncionalidades")
        self.verticalLayout.addWidget(self.LabelFuncionalidades)
        self.toolButton = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../assets/iconos/ventas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.toolButton)
        self.toolButton_5 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.toolButton_5.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../assets/iconos/Caja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.verticalLayout.addWidget(self.toolButton_5)
        self.toolButton_4 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMaximumSize(QtCore.QSize(16777215, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../assets/iconos/Credito.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon2)
        self.toolButton_4.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout.addWidget(self.toolButton_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMaximumSize(QtCore.QSize(16777215, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../assets/iconos/Egreso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout.addWidget(self.toolButton_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMaximumSize(QtCore.QSize(16777215, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../assets/iconos/Respaldo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout.addWidget(self.toolButton_2)
        self.LabelDatos = QtWidgets.QLabel(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelDatos.sizePolicy().hasHeightForWidth())
        self.LabelDatos.setSizePolicy(sizePolicy)
        self.LabelDatos.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setMaximumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setStyleSheet("#LabelDatos {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelDatos.setObjectName("LabelDatos")
        self.verticalLayout.addWidget(self.LabelDatos)
        self.toolButton_9 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setMaximumSize(QtCore.QSize(16777215, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../assets/iconos/Productos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon5)
        self.toolButton_9.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_9.setObjectName("toolButton_9")
        self.verticalLayout.addWidget(self.toolButton_9)
        self.toolButton_8 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setMaximumSize(QtCore.QSize(16777215, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../assets/iconos/CrediFactura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon6)
        self.toolButton_8.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_8.setObjectName("toolButton_8")
        self.verticalLayout.addWidget(self.toolButton_8)
        self.toolButton_7 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setMaximumSize(QtCore.QSize(16777215, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../assets/iconos/Facturas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_7.setObjectName("toolButton_7")
        self.verticalLayout.addWidget(self.toolButton_7)
        self.toolButton_6 = QtWidgets.QToolButton(self.navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setMaximumSize(QtCore.QSize(16777215, 40))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../assets/iconos/Reportes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon8)
        self.toolButton_6.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout.addWidget(self.toolButton_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_11 = QtWidgets.QPushButton(self.navbar)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-image: url(\'C:/Users/Sm/Downloads/iconos/Usuarios.png\'); /* Ruta de la imagen */\n"
"    background-repeat: no-repeat; /* Evita que la imagen se repita */\n"
"    background-position: left center; /* Alinea la imagen a la izquierda, centrada verticalmente */\n"
"    padding-left: 50px; /* Ajusta el espacio entre la imagen y el texto */\n"
"    padding-right: 10px; /* Opcional: para añadir un poco de espacio a la derecha del texto */\n"
"    text-align: left; /* Alinea el texto a la izquierda */\n"
"  \n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.navbar)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.horizontalLayout_2.addWidget(self.navbar)
        self.Contenido = QtWidgets.QWidget(self.Contenedor)
        self.Contenido.setStyleSheet("border-radius:15px;\n"
"    background-color: #f2f2f2; \n"
"")
        self.Contenido.setObjectName("Contenido")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Contenido)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.Contenido)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputCantidad = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputCantidad.sizePolicy().hasHeightForWidth())
        self.InputCantidad.setSizePolicy(sizePolicy)
        self.InputCantidad.setMinimumSize(QtCore.QSize(250, 50))
        self.InputCantidad.setMaximumSize(QtCore.QSize(250, 50))
        self.InputCantidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputCantidad.setObjectName("InputCantidad")
        self.gridLayout_2.addWidget(self.InputCantidad, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 9, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 5, 1, 1)
        self.Label_producto = QtWidgets.QLabel(self.widget_3)
        self.Label_producto.setStyleSheet("#Label_producto {\n"
"    font-size: 26px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.Label_producto.setObjectName("Label_producto")
        self.gridLayout_2.addWidget(self.Label_producto, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.InputCodigo = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputCodigo.sizePolicy().hasHeightForWidth())
        self.InputCodigo.setSizePolicy(sizePolicy)
        self.InputCodigo.setMinimumSize(QtCore.QSize(250, 50))
        self.InputCodigo.setMaximumSize(QtCore.QSize(250, 50))
        self.InputCodigo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputCodigo.setObjectName("InputCodigo")
        self.gridLayout_2.addWidget(self.InputCodigo, 5, 0, 1, 1)
        self.LabelVentasA = QtWidgets.QLabel(self.widget_3)
        self.LabelVentasA.setStyleSheet("#LabelVentasA {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 34px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelVentasA.setObjectName("LabelVentasA")
        self.gridLayout_2.addWidget(self.LabelVentasA, 0, 0, 1, 1)
        self.InputNombre = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputNombre.sizePolicy().hasHeightForWidth())
        self.InputNombre.setSizePolicy(sizePolicy)
        self.InputNombre.setMinimumSize(QtCore.QSize(250, 50))
        self.InputNombre.setMaximumSize(QtCore.QSize(250, 50))
        self.InputNombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputNombre.setObjectName("InputNombre")
        self.gridLayout_2.addWidget(self.InputNombre, 5, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: red; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 9, 5, 1, 1)
        self.InputPrecioUnitario = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPrecioUnitario.sizePolicy().hasHeightForWidth())
        self.InputPrecioUnitario.setSizePolicy(sizePolicy)
        self.InputPrecioUnitario.setMinimumSize(QtCore.QSize(250, 50))
        self.InputPrecioUnitario.setMaximumSize(QtCore.QSize(250, 50))
        self.InputPrecioUnitario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputPrecioUnitario.setObjectName("InputPrecioUnitario")
        self.gridLayout_2.addWidget(self.InputPrecioUnitario, 5, 5, 1, 1)
        self.InputMarca = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputMarca.sizePolicy().hasHeightForWidth())
        self.InputMarca.setSizePolicy(sizePolicy)
        self.InputMarca.setMinimumSize(QtCore.QSize(250, 50))
        self.InputMarca.setMaximumSize(QtCore.QSize(250, 50))
        self.InputMarca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputMarca.setObjectName("InputMarca")
        self.gridLayout_2.addWidget(self.InputMarca, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(250, 50))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 9, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 5, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.Contenido)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_2.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: #e0e0e0; /* Color gris claro */\n"
"    gridline-color: #f0f0f0; /* Color de las líneas */\n"
"    font: 12pt \"Arial\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #d0d0d0; /* Fondo gris oscuro para las cabeceras */\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #c0c0c0;\n"
"    color: black;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border: 1px solid transparent; /* Evita bordes visibles en celdas */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #a0a0a0; /* Color de selección gris */\n"
"    color: white;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.Contenido)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.horizontalLayout.addWidget(self.Contenedor)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LabelFuncionalidades.setText(_translate("Form", "Funcionalidades"))
        self.toolButton.setText(_translate("Form", "Ventas"))
        self.toolButton_5.setText(_translate("Form", "Caja"))
        self.toolButton_4.setText(_translate("Form", "Credito"))
        self.toolButton_3.setText(_translate("Form", "Egreso"))
        self.toolButton_2.setText(_translate("Form", "Respaldo"))
        self.LabelDatos.setText(_translate("Form", "Datos"))
        self.toolButton_9.setText(_translate("Form", "Productos"))
        self.toolButton_8.setText(_translate("Form", "CrediFactura"))
        self.toolButton_7.setText(_translate("Form", "Factura"))
        self.toolButton_6.setText(_translate("Form", "Reportes"))
        self.pushButton_11.setText(_translate("Form", "Control Usuarios"))
        self.pushButton_10.setText(_translate("Form", "Usuario"))
        self.label_5.setText(_translate("Form", "Nombre "))
        self.label_7.setText(_translate("Form", "Cantidad "))
        self.label_6.setText(_translate("Form", "Marca"))
        self.pushButton_3.setText(_translate("Form", "Agregar Producto"))
        self.label.setText(_translate("Form", "Precio Unitario"))
        self.Label_producto.setText(_translate("Form", "Producto"))
        self.label_8.setText(_translate("Form", "Valor Domicilio"))
        self.LabelVentasA.setText(_translate("Form", "Ventas"))
        self.pushButton_4.setText(_translate("Form", "Eliminar"))
        self.label_3.setText(_translate("Form", "Codigo"))
        self.pushButton.setText(_translate("Form", "Factura A"))
        self.pushButton_2.setText(_translate("Form", "Factura B"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Producto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Marca"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Categoria"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Precio Unitario"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Cantidad "))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
