# Form implementation generated from reading ui file 'd:\SYSTOCK\SYSTOCK\DESARROLLO\python\programacion_ladynails\Project_LadyNails\app\ui\Egreso.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1640, 1081)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contenedor = QtWidgets.QWidget(parent=Form)
        self.Contenedor.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    margin-top:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  rgb(50, 50, 50); /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: left; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #f2f2f2; /* Gris claro al pasar el mouse */\n"
"    cursor: pointer;\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"    border: none; /* Sin bordes visibles */\n"
"    padding: 4px; /* Espaciado interno entre el texto y los bordes */\n"
"    margin-right: 5px; /* Espaciado externo solo a la derecha */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    color: black; /* Texto negro */\n"
"    text-align: left; /* Texto alineado a la izquierda */\n"
"    font-size: 18px; /* Tamaño del texto */\n"
"}\n"
"\n"
"/* Cuando el QLineEdit está enfocado (se está escribiendo) */\n"
"QLineEdit:focus {\n"
"    background-color: rgb(230, 230, 250); /* Color de fondo cuando el campo está activo */\n"
"    border: 1px solid rgb(0, 0, 0); /* Borde negro al estar activo */\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    color:  black; /* Color del texto */\n"
"    margin-right: 10px; /* Espaciado a la derecha */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    text-align: left; /* Alineación del texto a la izquierda */\n"
"}\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: #ffffff; /* Fondo blanco para la tabla */\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
"    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
"    color: black; /* Texto negro para celdas seleccionadas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border: none; \n"
"    background-color: #f2f2f2; \n"
"    font-weight: normal; /* No negritas */\n"
"    text-align: center; /* Centrado del texto en los encabezados */\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
"}\n"
"\n"
"QHeaderView::section:focus {\n"
"    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
"    border: none; /* Sin borde cuando está en foco */\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
"    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"}\n"
"\n"
"QTableWidget::verticalHeader {\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    font-weight: normal; /* No negritas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"\n"
"/* Personalización de la barra de desplazamiento */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    width: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-height: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
"    height: 0px; /* Sin altura para los botones */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    height: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-width: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
"    width: 0px; /* Sin ancho para los botones */\n"
"}\n"
"\n"
"\n"
"")
        self.Contenedor.setObjectName("Contenedor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenedor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Navbar = QtWidgets.QWidget(parent=self.Contenedor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Navbar.sizePolicy().hasHeightForWidth())
        self.Navbar.setSizePolicy(sizePolicy)
        self.Navbar.setMinimumSize(QtCore.QSize(250, 0))
        self.Navbar.setStyleSheet("#navbar {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border-right: 1px solid black; /* Borde negro en el lado derecho */\n"
"}\n"
"")
        self.Navbar.setObjectName("Navbar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Navbar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelImgNavbar = QtWidgets.QLabel(parent=self.Navbar)
        self.LabelImgNavbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.LabelImgNavbar.sizePolicy().hasHeightForWidth())
        self.LabelImgNavbar.setSizePolicy(sizePolicy)
        self.LabelImgNavbar.setMinimumSize(QtCore.QSize(100, 50))
        self.LabelImgNavbar.setMaximumSize(QtCore.QSize(260, 70))
        self.LabelImgNavbar.setStyleSheet("#LabelImg {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: 100% 100%; /* Ajusta la imagen para que ocupe todo el área del label */\n"
"    height: 200px; /* Ajusta la altura del QLabel */\n"
"    width: 300px; /* Ajusta el ancho del QLabel */\n"
"}\n"
"")
        self.LabelImgNavbar.setText("")
        self.LabelImgNavbar.setPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/Letras-sinfondo.png"))
        self.LabelImgNavbar.setScaledContents(True)
        self.LabelImgNavbar.setObjectName("LabelImgNavbar")
        self.verticalLayout.addWidget(self.LabelImgNavbar)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.LabelFuncionalidades = QtWidgets.QLabel(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelFuncionalidades.sizePolicy().hasHeightForWidth())
        self.LabelFuncionalidades.setSizePolicy(sizePolicy)
        self.LabelFuncionalidades.setMinimumSize(QtCore.QSize(250, 30))
        self.LabelFuncionalidades.setMaximumSize(QtCore.QSize(300, 50))
        self.LabelFuncionalidades.setStyleSheet("#LabelFuncionalidades {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelFuncionalidades.setObjectName("LabelFuncionalidades")
        self.verticalLayout.addWidget(self.LabelFuncionalidades)
        self.BtnVentas = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnVentas.sizePolicy().hasHeightForWidth())
        self.BtnVentas.setSizePolicy(sizePolicy)
        self.BtnVentas.setMinimumSize(QtCore.QSize(0, 0))
        self.BtnVentas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnVentas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BtnVentas.setStyleSheet("\n"
"    padding-left: 10px; /* Distancia entre icono y borde izquierdo */\n"
"    text-align: right; /* Texto más hacia la derecha */\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/ventas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnVentas.setIcon(icon)
        self.BtnVentas.setIconSize(QtCore.QSize(30, 30))
        self.BtnVentas.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnVentas.setAutoRaise(False)
        self.BtnVentas.setObjectName("BtnVentas")
        self.verticalLayout.addWidget(self.BtnVentas)
        self.BtnCaja = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCaja.sizePolicy().hasHeightForWidth())
        self.BtnCaja.setSizePolicy(sizePolicy)
        self.BtnCaja.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCaja.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BtnCaja.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Caja.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnCaja.setIcon(icon1)
        self.BtnCaja.setIconSize(QtCore.QSize(30, 30))
        self.BtnCaja.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnCaja.setObjectName("BtnCaja")
        self.verticalLayout.addWidget(self.BtnCaja)
        self.BtnCredito = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCredito.sizePolicy().hasHeightForWidth())
        self.BtnCredito.setSizePolicy(sizePolicy)
        self.BtnCredito.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCredito.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Credito.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnCredito.setIcon(icon2)
        self.BtnCredito.setIconSize(QtCore.QSize(30, 30))
        self.BtnCredito.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnCredito.setObjectName("BtnCredito")
        self.verticalLayout.addWidget(self.BtnCredito)
        self.BtnEgreso = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnEgreso.sizePolicy().hasHeightForWidth())
        self.BtnEgreso.setSizePolicy(sizePolicy)
        self.BtnEgreso.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnEgreso.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Egreso.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnEgreso.setIcon(icon3)
        self.BtnEgreso.setIconSize(QtCore.QSize(30, 30))
        self.BtnEgreso.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnEgreso.setObjectName("BtnEgreso")
        self.verticalLayout.addWidget(self.BtnEgreso)
        self.BtnRespaldo = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnRespaldo.sizePolicy().hasHeightForWidth())
        self.BtnRespaldo.setSizePolicy(sizePolicy)
        self.BtnRespaldo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnRespaldo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Respaldo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnRespaldo.setIcon(icon4)
        self.BtnRespaldo.setIconSize(QtCore.QSize(30, 30))
        self.BtnRespaldo.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnRespaldo.setObjectName("BtnRespaldo")
        self.verticalLayout.addWidget(self.BtnRespaldo)
        self.LabelDatos = QtWidgets.QLabel(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelDatos.sizePolicy().hasHeightForWidth())
        self.LabelDatos.setSizePolicy(sizePolicy)
        self.LabelDatos.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setMaximumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setStyleSheet("#LabelDatos {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelDatos.setObjectName("LabelDatos")
        self.verticalLayout.addWidget(self.LabelDatos)
        self.BtnProductos = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnProductos.sizePolicy().hasHeightForWidth())
        self.BtnProductos.setSizePolicy(sizePolicy)
        self.BtnProductos.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnProductos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Productos.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnProductos.setIcon(icon5)
        self.BtnProductos.setIconSize(QtCore.QSize(30, 30))
        self.BtnProductos.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnProductos.setObjectName("BtnProductos")
        self.verticalLayout.addWidget(self.BtnProductos)
        self.BtnCrediFactura = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCrediFactura.sizePolicy().hasHeightForWidth())
        self.BtnCrediFactura.setSizePolicy(sizePolicy)
        self.BtnCrediFactura.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCrediFactura.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/CrediFactura.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnCrediFactura.setIcon(icon6)
        self.BtnCrediFactura.setIconSize(QtCore.QSize(30, 30))
        self.BtnCrediFactura.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnCrediFactura.setObjectName("BtnCrediFactura")
        self.verticalLayout.addWidget(self.BtnCrediFactura)
        self.BtnFacturas = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnFacturas.sizePolicy().hasHeightForWidth())
        self.BtnFacturas.setSizePolicy(sizePolicy)
        self.BtnFacturas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnFacturas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Facturas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnFacturas.setIcon(icon7)
        self.BtnFacturas.setIconSize(QtCore.QSize(30, 30))
        self.BtnFacturas.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnFacturas.setObjectName("BtnFacturas")
        self.verticalLayout.addWidget(self.BtnFacturas)
        self.BtnReportes = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnReportes.sizePolicy().hasHeightForWidth())
        self.BtnReportes.setSizePolicy(sizePolicy)
        self.BtnReportes.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnReportes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Reportes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnReportes.setIcon(icon8)
        self.BtnReportes.setIconSize(QtCore.QSize(30, 30))
        self.BtnReportes.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnReportes.setObjectName("BtnReportes")
        self.verticalLayout.addWidget(self.BtnReportes)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.BtnControlUsuario = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnControlUsuario.sizePolicy().hasHeightForWidth())
        self.BtnControlUsuario.setSizePolicy(sizePolicy)
        self.BtnControlUsuario.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnControlUsuario.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Usuarios.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnControlUsuario.setIcon(icon9)
        self.BtnControlUsuario.setIconSize(QtCore.QSize(30, 30))
        self.BtnControlUsuario.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnControlUsuario.setObjectName("BtnControlUsuario")
        self.verticalLayout.addWidget(self.BtnControlUsuario)
        self.BtnUsuario = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnUsuario.sizePolicy().hasHeightForWidth())
        self.BtnUsuario.setSizePolicy(sizePolicy)
        self.BtnUsuario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BtnUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/perfil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnUsuario.setIcon(icon10)
        self.BtnUsuario.setIconSize(QtCore.QSize(60, 60))
        self.BtnUsuario.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BtnUsuario.setObjectName("BtnUsuario")
        self.verticalLayout.addWidget(self.BtnUsuario)
        self.horizontalLayout_2.addWidget(self.Navbar)
        self.Contenido = QtWidgets.QStackedWidget(parent=self.Contenedor)
        self.Contenido.setStyleSheet("margin-left:10px;\n"
"border-radius:15px;\n"
"background-color: #f2f2f2; \n"
"")
        self.Contenido.setObjectName("Contenido")
        self.ContenidoPage1 = QtWidgets.QWidget()
        self.ContenidoPage1.setObjectName("ContenidoPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ContenidoPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.ContenidoPage1)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputDescripcionEgreso = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputDescripcionEgreso.sizePolicy().hasHeightForWidth())
        self.InputDescripcionEgreso.setSizePolicy(sizePolicy)
        self.InputDescripcionEgreso.setMinimumSize(QtCore.QSize(250, 50))
        self.InputDescripcionEgreso.setMaximumSize(QtCore.QSize(250, 50))
        self.InputDescripcionEgreso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputDescripcionEgreso.setObjectName("InputDescripcionEgreso")
        self.gridLayout_2.addWidget(self.InputDescripcionEgreso, 3, 1, 1, 1)
        self.LabelVentasA = QtWidgets.QLabel(parent=self.widget_3)
        self.LabelVentasA.setStyleSheet("#LabelVentasA {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 34px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelVentasA.setObjectName("LabelVentasA")
        self.gridLayout_2.addWidget(self.LabelVentasA, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.InputFechaEgreso = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputFechaEgreso.sizePolicy().hasHeightForWidth())
        self.InputFechaEgreso.setSizePolicy(sizePolicy)
        self.InputFechaEgreso.setMinimumSize(QtCore.QSize(250, 50))
        self.InputFechaEgreso.setMaximumSize(QtCore.QSize(250, 50))
        self.InputFechaEgreso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputFechaEgreso.setObjectName("InputFechaEgreso")
        self.gridLayout_2.addWidget(self.InputFechaEgreso, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 3, 1, 1)
        self.InputTipoGasto = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputTipoGasto.sizePolicy().hasHeightForWidth())
        self.InputTipoGasto.setSizePolicy(sizePolicy)
        self.InputTipoGasto.setMinimumSize(QtCore.QSize(250, 50))
        self.InputTipoGasto.setMaximumSize(QtCore.QSize(250, 50))
        self.InputTipoGasto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputTipoGasto.setObjectName("InputTipoGasto")
        self.gridLayout_2.addWidget(self.InputTipoGasto, 3, 0, 1, 1)
        self.InputPagoEgreso = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPagoEgreso.sizePolicy().hasHeightForWidth())
        self.InputPagoEgreso.setSizePolicy(sizePolicy)
        self.InputPagoEgreso.setMinimumSize(QtCore.QSize(250, 50))
        self.InputPagoEgreso.setMaximumSize(QtCore.QSize(250, 50))
        self.InputPagoEgreso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputPagoEgreso.setObjectName("InputPagoEgreso")
        self.gridLayout_2.addWidget(self.InputPagoEgreso, 3, 2, 1, 1)
        self.BtnMetodoPago = QtWidgets.QPushButton(parent=self.widget_3)
        self.BtnMetodoPago.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.BtnMetodoPago.setObjectName("BtnMetodoPago")
        self.gridLayout_2.addWidget(self.BtnMetodoPago, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.BtnRegistrarEgreso = QtWidgets.QPushButton(parent=self.widget_3)
        self.BtnRegistrarEgreso.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    margin-top:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}")
        self.BtnRegistrarEgreso.setObjectName("BtnRegistrarEgreso")
        self.gridLayout_2.addWidget(self.BtnRegistrarEgreso, 5, 2, 1, 1)
        self.BtnEliminar = QtWidgets.QPushButton(parent=self.widget_3)
        self.BtnEliminar.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: red; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    margin-top:20px;\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/eliminar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BtnEliminar.setIcon(icon11)
        self.BtnEliminar.setIconSize(QtCore.QSize(30, 30))
        self.BtnEliminar.setObjectName("BtnEliminar")
        self.gridLayout_2.addWidget(self.BtnEliminar, 5, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget = QtWidgets.QWidget(parent=self.ContenidoPage1)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TablaEgreso = QtWidgets.QTableWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TablaEgreso.sizePolicy().hasHeightForWidth())
        self.TablaEgreso.setSizePolicy(sizePolicy)
        self.TablaEgreso.setMinimumSize(QtCore.QSize(750, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TablaEgreso.setFont(font)
        self.TablaEgreso.setStyleSheet("\n"
"QTableWidget {\n"
"    border: none;\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"    font-size: 18px; /* Tamaño de letra */\n"
"    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
"    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
"    color: black; /* Texto negro para celdas seleccionadas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border: none; \n"
"    background-color: #f2f2f2; \n"
"    font-size: 18px; /* Tamaño de letra */\n"
"    font-weight: normal; /* No negritas */\n"
"    text-align: center; /* Centrado del texto en los encabezados */\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
"}\n"
"\n"
"QHeaderView::section:focus {\n"
"    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
"    border: none; /* Sin borde cuando está en foco */\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
"    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"}\n"
"\n"
"QTableWidget::verticalHeader {\n"
"    background-color: #f2f2f2;\n"
"    font-size: 23px;\n"
"    border: none;\n"
"    font-weight: normal; /* No negritas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"/* Personalización de la barra de desplazamiento */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    width: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"    margin: 0px 2px 0px 0px; /* Un pequeño margen para el desplazamiento */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-height: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
"    height: 0px; /* Sin altura para los botones */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    height: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"    margin: 0px 0px 2px 0px; /* Un pequeño margen para el desplazamiento */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-width: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"")
        self.TablaEgreso.setObjectName("TablaEgreso")
        self.TablaEgreso.setColumnCount(6)
        self.TablaEgreso.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEgreso.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        self.TablaEgreso.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TablaEgreso.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TablaEgreso.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TablaEgreso.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TablaEgreso.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TablaEgreso.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.TablaEgreso, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(parent=self.ContenidoPage1)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Contenido.addWidget(self.ContenidoPage1)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.horizontalLayout.addWidget(self.Contenedor)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LabelFuncionalidades.setText(_translate("Form", "Funcionalidades"))
        self.BtnVentas.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.BtnVentas.setText(_translate("Form", "   Ventas"))
        self.BtnCaja.setText(_translate("Form", "   Caja"))
        self.BtnCredito.setText(_translate("Form", "   Credito"))
        self.BtnEgreso.setText(_translate("Form", "   Egreso"))
        self.BtnRespaldo.setText(_translate("Form", "   Respaldo"))
        self.LabelDatos.setText(_translate("Form", "Datos"))
        self.BtnProductos.setText(_translate("Form", "   Productos"))
        self.BtnCrediFactura.setText(_translate("Form", "   CrediFactura"))
        self.BtnFacturas.setText(_translate("Form", "   Factura"))
        self.BtnReportes.setText(_translate("Form", "   Reportes"))
        self.BtnControlUsuario.setText(_translate("Form", "   Control Usuarios"))
        self.BtnUsuario.setText(_translate("Form", "   Usuario"))
        self.LabelVentasA.setText(_translate("Form", "Egresos"))
        self.label_7.setText(_translate("Form", "Pago"))
        self.label_5.setText(_translate("Form", "Descripcion"))
        self.label.setText(_translate("Form", "Fecha"))
        self.BtnMetodoPago.setText(_translate("Form", "metodo de pago"))
        self.label_6.setText(_translate("Form", "Metodo de Pago"))
        self.label_3.setText(_translate("Form", "Tipo de Gasto"))
        self.BtnRegistrarEgreso.setText(_translate("Form", "Registar Egreso"))
        self.BtnEliminar.setText(_translate("Form", "   Eliminar Egreso"))
        item = self.TablaEgreso.verticalHeaderItem(0)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(1)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(2)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(3)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(4)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(5)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(6)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(7)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(8)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(9)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(10)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(11)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(12)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(13)
        item.setText(_translate("Form", "Nueva fila"))
        item = self.TablaEgreso.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaEgreso.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaEgreso.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID Egr"))
        item = self.TablaEgreso.horizontalHeaderItem(1)
        item.setText(_translate("Form", "T.Gasto"))
        item = self.TablaEgreso.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Descripcion"))
        item = self.TablaEgreso.horizontalHeaderItem(3)
        item.setText(_translate("Form", "M.Pago"))
        item = self.TablaEgreso.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Monto"))
        item = self.TablaEgreso.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fecha"))
