# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CONTENEDEDOR1(object):
    def setupUi(self, CONTENEDEDOR1):
        CONTENEDEDOR1.setObjectName("CONTENEDEDOR1")
        CONTENEDEDOR1.resize(815, 840)
        CONTENEDEDOR1.setMinimumSize(QtCore.QSize(0, 0))
        CONTENEDEDOR1.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(CONTENEDEDOR1)
        self.gridLayout.setObjectName("gridLayout")
        self.CONTENEDOR2 = QtWidgets.QWidget(CONTENEDEDOR1)
        self.CONTENEDOR2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CONTENEDOR2.setObjectName("CONTENEDOR2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CONTENEDOR2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CONTENEDOR3 = QtWidgets.QWidget(self.CONTENEDOR2)
        self.CONTENEDOR3.setMinimumSize(QtCore.QSize(200, 0))
        self.CONTENEDOR3.setMaximumSize(QtCore.QSize(500, 1000))
        self.CONTENEDOR3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.CONTENEDOR3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.CONTENEDOR3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CONTENEDOR3.setStyleSheet("")
        self.CONTENEDOR3.setObjectName("CONTENEDOR3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CONTENEDOR3)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BtnLogin = QtWidgets.QPushButton(self.CONTENEDOR3)
        self.BtnLogin.setMinimumSize(QtCore.QSize(200, 0))
        self.BtnLogin.setMaximumSize(QtCore.QSize(500, 50))
        self.BtnLogin.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Fondo negro */\n"
"    color: #FFFFFF; /* Letra blanca */\n"
"    border: 2px solid #FFFFFF; /* Borde blanco */\n"
"    border-radius: 8px; /* Bordes redondeados */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de la letra */\n"
"    font-weight: bold; /* Letra en negrita */\n"
"    transition: all 0.3s ease; /* Transición suave para hover y pressed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444; /* Fondo gris oscuro al pasar el mouse */\n"
"    transform: scale(1.05); /* Efecto de aumentar tamaño */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #555555; /* Fondo gris más claro al hacer clic */\n"
"    color: #FFFFFF; /* Letra blanca */\n"
"    border-color: #FFFFFF; /* Borde blanco */\n"
"    transform: scale(0.98); /* Efecto de reducir tamaño */\n"
"}\n"
"")
        self.BtnLogin.setObjectName("BtnLogin")
        self.BtnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout_2.addWidget(self.BtnLogin, 8, 1, 1, 1)
        self.InputPassword = QtWidgets.QLineEdit(self.CONTENEDOR3)
        self.InputPassword.setMaximumSize(QtCore.QSize(500, 50))
        self.InputPassword.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;  /* Fondo blanco */\n"
"    border: 2px solid #D3D3D3;  /* Borde gris suave */\n"
"    border-radius: 10px;        /* Bordes redondeados */\n"
"    padding: 10px;              /* Espaciado interno */\n"
"    font-size: 18px;            /* Tamaño de la letra */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente por defecto */\n"
"    color: #A9A9A9;             /* Letra gris suave */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #000000;      /* Borde verde al hacer foco */\n"
"    background-color: #ffffff;  /* Fondo blanco al hacer foco */\n"
"    color: #000000;             /* Letra negra al escribir */\n"
"}\n"
"")
        self.InputPassword.setObjectName("InputPassword")
        self.gridLayout_2.addWidget(self.InputPassword, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 11, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.InputNombreUsuario = QtWidgets.QLineEdit(self.CONTENEDOR3)
        self.InputNombreUsuario.setMaximumSize(QtCore.QSize(500, 50))
        self.InputNombreUsuario.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;  /* Fondo blanco */\n"
"    border: 2px solid #D3D3D3;  /* Borde gris suave */\n"
"    border-radius: 10px;        /* Bordes redondeados */\n"
"    padding: 10px;              /* Espaciado interno */\n"
"    font-size: 18px;            /* Tamaño de la letra */\n"
"    font-family: \"Arial\", sans-serif; /* Fuente por defecto */\n"
"    color: #A9A9A9;             /* Letra gris suave */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #000000;      /* Borde verde al hacer foco */\n"
"    background-color: #ffffff;  /* Fondo blanco al hacer foco */\n"
"    color: #000000;             /* Letra negra al escribir */\n"
"}")
        self.InputNombreUsuario.setObjectName("InputNombreUsuario")
        self.gridLayout_2.addWidget(self.InputNombreUsuario, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 11, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.BtnRol = QtWidgets.QPushButton(self.CONTENEDOR3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.BtnRol.sizePolicy().hasHeightForWidth())
        self.BtnRol.setSizePolicy(sizePolicy)
        self.BtnRol.setMinimumSize(QtCore.QSize(0, 0))
        self.BtnRol.setMaximumSize(QtCore.QSize(500, 50))
        self.BtnRol.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.BtnRol.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BtnRol.setStyleSheet("QPushButton {\n"
"    background-color: #000000; /* Fondo negro */\n"
"    color: #FFFFFF; /* Letra blanca */\n"
"    border: 2px solid #FFFFFF; /* Borde blanco */\n"
"    border-radius: 8px; /* Bordes redondeados */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de la letra */\n"
"    font-weight: bold; /* Letra en negrita */\n"
"    transition: all 0.3s ease; /* Transición suave para hover y pressed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #444444; /* Fondo gris oscuro al pasar el mouse */\n"
"    transform: scale(1.05); /* Efecto de aumentar tamaño */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #555555; /* Fondo gris más claro al hacer clic */\n"
"    color: #FFFFFF; /* Letra blanca */\n"
"    border-color: #FFFFFF; /* Borde blanco */\n"
"    transform: scale(0.98); /* Efecto de reducir tamaño */\n"
"}\n"
"")
        self.BtnRol.setObjectName("BtnRol")
        self.BtnRol.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout_2.addWidget(self.BtnRol, 5, 1, 1, 1)
        self.BtnRol.clicked.connect(self.cambiarTextoBoton)
        self.IMAGEN = QtWidgets.QLabel(self.CONTENEDOR3)
        self.IMAGEN.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.IMAGEN.sizePolicy().hasHeightForWidth())
        self.IMAGEN.setSizePolicy(sizePolicy)
        self.IMAGEN.setMaximumSize(QtCore.QSize(600, 180))
        self.IMAGEN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.IMAGEN.setAutoFillBackground(False)
        self.IMAGEN.setStyleSheet("")
        self.IMAGEN.setText("")
        self.IMAGEN.setPixmap(QtGui.QPixmap("assets/Letras-sinfondo.png"))
        self.IMAGEN.setScaledContents(True)
        self.IMAGEN.setObjectName("IMAGEN")
        self.gridLayout_2.addWidget(self.IMAGEN, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.CONTENEDOR3)
        self.gridLayout.addWidget(self.CONTENEDOR2, 0, 0, 1, 1)

        self.retranslateUi(CONTENEDEDOR1)
        QtCore.QMetaObject.connectSlotsByName(CONTENEDEDOR1)

    def retranslateUi(self, CONTENEDEDOR1):
        _translate = QtCore.QCoreApplication.translate
        CONTENEDEDOR1.setWindowTitle(_translate("CONTENEDEDOR1", "Form"))
        self.BtnLogin.setText(_translate("CONTENEDEDOR1", "Iniciar Sesion"))
        self.InputPassword.setText(_translate("CONTENEDEDOR1", "contraseña"))
        self.InputNombreUsuario.setText(_translate("CONTENEDEDOR1", "Usuario"))
        self.BtnRol.setText(_translate("CONTENEDEDOR1", "ADMINISTRADOR"))

    def cambiarTextoBoton(self):
        # Verificar el texto actual y alternar entre 'ADMINISTRADOR' y 'ASESOR'
        if self.BtnRol.text() == "ADMINISTRADOR":
            self.BtnRol.setText("ASESOR")
        else:
            self.BtnRol.setText("ADMINISTRADOR")
