# Form implementation generated from reading ui file 'd:\SYSTOCK\SYSTOCK\DESARROLLO\python\programacion_ladynails\Project_LadyNails\app\ui\Reportes.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1639, 1083)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Contenedor = QtWidgets.QWidget(parent=Form)
        self.Contenedor.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: black; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QToolButton {\n"
            "    background-color: white; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  rgb(50, 50, 50); /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: left; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    cursor: pointer;\n"
            "}\n"
            "\n"
            "QToolButton:hover {\n"
            "    background-color: #f2f2f2; /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer;\n"
            "}\n"
            "QLineEdit {\n"
            "    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
            "    border: none; /* Sin bordes visibles */\n"
            "    padding: 4px; /* Espaciado interno entre el texto y los bordes */\n"
            "    margin-right: 5px; /* Espaciado externo solo a la derecha */\n"
            "    border-radius: 10px; /* Bordes redondeados */\n"
            "    color: black; /* Texto negro */\n"
            "    text-align: left; /* Texto alineado a la izquierda */\n"
            "    font-size: 18px; /* Tamaño del texto */\n"
            "}\n"
            "\n"
            "/* Cuando el QLineEdit está enfocado (se está escribiendo) */\n"
            "QLineEdit:focus {\n"
            "    background-color: rgb(230, 230, 250); /* Color de fondo cuando el campo está activo */\n"
            "    border: 1px solid rgb(0, 0, 0); /* Borde negro al estar activo */\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    font-size: 20px; /* Tamaño de fuente */\n"
            "    color:  black; /* Color del texto */\n"
            "    margin-right: 10px; /* Espaciado a la derecha */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    text-align: left; /* Alineación del texto a la izquierda */\n"
            "}\n"
            "QTableWidget {\n"
            "    border: none;\n"
            "    background-color: #ffffff; /* Fondo blanco para la tabla */\n"
            "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
            "}\n"
            "\n"
            "QTableWidget::item {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
            "    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
            "}\n"
            "\n"
            "QTableWidget::item:selected {\n"
            "    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
            "    color: black; /* Texto negro para celdas seleccionadas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "\n"
            "QHeaderView::section {\n"
            "    border: none; \n"
            "    background-color: #f2f2f2; \n"
            "    font-weight: normal; /* No negritas */\n"
            "    text-align: center; /* Centrado del texto en los encabezados */\n"
            "    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
            "}\n"
            "\n"
            "QHeaderView::section:focus {\n"
            "    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
            "    border: none; /* Sin borde cuando está en foco */\n"
            "}\n"
            "\n"
            "QTableWidget::item:focus {\n"
            "    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
            "    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
            "}\n"
            "\n"
            "QTableCornerButton::section {\n"
            "    background-color: #f2f2f2; \n"
            "    border: none; \n"
            "}\n"
            "\n"
            "QTableWidget::verticalHeader {\n"
            "    background-color: #f2f2f2;\n"
            "    border: none;\n"
            "    font-weight: normal; /* No negritas */\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
            "}\n"
            "\n"
            "/* Personalización de la barra de desplazamiento */\n"
            "QScrollBar:vertical {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    width: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-height: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
            "    border: none;\n"
            "    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
            "    height: 0px; /* Sin altura para los botones */\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {\n"
            "    border: none;\n"
            "    background: #f7f7f7; /* Fondo de la barra */\n"
            "    height: 8px; /* Barra más delgada */\n"
            "    border-radius: 4px; /* Bordes más redondeados */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal {\n"
            "    background: #bbb; /* Fondo del control deslizante */\n"
            "    min-width: 20px; /* Control deslizante más delgado */\n"
            "    border-radius: 4px; /* Bordes redondeados */\n"
            "    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal:hover {\n"
            "    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
            "    border: none;\n"
            "    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
            "    width: 0px; /* Sin ancho para los botones */\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.Contenedor.setObjectName("Contenedor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenedor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Navbar = QtWidgets.QWidget(parent=self.Contenedor)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Navbar.sizePolicy().hasHeightForWidth())
        self.Navbar.setSizePolicy(sizePolicy)
        self.Navbar.setMinimumSize(QtCore.QSize(250, 0))
        self.Navbar.setStyleSheet(
            "#navbar {\n"
            "    background-color: white; /* Fondo blanco */\n"
            "    border-right: 1px solid black; /* Borde negro en el lado derecho */\n"
            "}\n"
            ""
        )
        self.Navbar.setObjectName("Navbar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Navbar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelImgNavbar = QtWidgets.QLabel(parent=self.Navbar)
        self.LabelImgNavbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(
            self.LabelImgNavbar.sizePolicy().hasHeightForWidth()
        )
        self.LabelImgNavbar.setSizePolicy(sizePolicy)
        self.LabelImgNavbar.setMinimumSize(QtCore.QSize(100, 50))
        self.LabelImgNavbar.setMaximumSize(QtCore.QSize(260, 70))
        self.LabelImgNavbar.setStyleSheet(
            "#LabelImg {\n"
            "    background-position: center;\n"
            "    background-repeat: no-repeat;\n"
            "    background-size: 100% 100%; /* Ajusta la imagen para que ocupe todo el área del label */\n"
            "    height: 200px; /* Ajusta la altura del QLabel */\n"
            "    width: 300px; /* Ajusta el ancho del QLabel */\n"
            "}\n"
            ""
        )
        self.LabelImgNavbar.setText("")
        self.LabelImgNavbar.setPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/Letras-sinfondo.png"
            )
        )
        self.LabelImgNavbar.setScaledContents(True)
        self.LabelImgNavbar.setObjectName("LabelImgNavbar")
        self.verticalLayout.addWidget(self.LabelImgNavbar)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            30,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        self.verticalLayout.addItem(spacerItem)
        self.LabelFuncionalidades = QtWidgets.QLabel(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LabelFuncionalidades.sizePolicy().hasHeightForWidth()
        )
        self.LabelFuncionalidades.setSizePolicy(sizePolicy)
        self.LabelFuncionalidades.setMinimumSize(QtCore.QSize(250, 30))
        self.LabelFuncionalidades.setMaximumSize(QtCore.QSize(300, 50))
        self.LabelFuncionalidades.setStyleSheet(
            "#LabelFuncionalidades {\n"
            "    font-weight: bold; /* Negrita */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "}\n"
            ""
        )
        self.LabelFuncionalidades.setObjectName("LabelFuncionalidades")
        self.verticalLayout.addWidget(self.LabelFuncionalidades)
        self.BtnVentas = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnVentas.sizePolicy().hasHeightForWidth())
        self.BtnVentas.setSizePolicy(sizePolicy)
        self.BtnVentas.setMinimumSize(QtCore.QSize(0, 0))
        self.BtnVentas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnVentas.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.BtnVentas.setStyleSheet(
            "\n"
            "    padding-left: 10px; /* Distancia entre icono y borde izquierdo */\n"
            "    text-align: right; /* Texto más hacia la derecha */\n"
            "\n"
            ""
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/ventas.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnVentas.setIcon(icon)
        self.BtnVentas.setIconSize(QtCore.QSize(30, 30))
        self.BtnVentas.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnVentas.setAutoRaise(False)
        self.BtnVentas.setObjectName("BtnVentas")
        self.verticalLayout.addWidget(self.BtnVentas)
        self.BtnCaja = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCaja.sizePolicy().hasHeightForWidth())
        self.BtnCaja.setSizePolicy(sizePolicy)
        self.BtnCaja.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCaja.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BtnCaja.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Caja.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnCaja.setIcon(icon1)
        self.BtnCaja.setIconSize(QtCore.QSize(30, 30))
        self.BtnCaja.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnCaja.setObjectName("BtnCaja")
        self.verticalLayout.addWidget(self.BtnCaja)
        self.BtnCredito = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCredito.sizePolicy().hasHeightForWidth())
        self.BtnCredito.setSizePolicy(sizePolicy)
        self.BtnCredito.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCredito.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Credito.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnCredito.setIcon(icon2)
        self.BtnCredito.setIconSize(QtCore.QSize(30, 30))
        self.BtnCredito.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnCredito.setObjectName("BtnCredito")
        self.verticalLayout.addWidget(self.BtnCredito)
        self.BtnEgreso = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnEgreso.sizePolicy().hasHeightForWidth())
        self.BtnEgreso.setSizePolicy(sizePolicy)
        self.BtnEgreso.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnEgreso.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Egreso.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnEgreso.setIcon(icon3)
        self.BtnEgreso.setIconSize(QtCore.QSize(30, 30))
        self.BtnEgreso.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnEgreso.setObjectName("BtnEgreso")
        self.verticalLayout.addWidget(self.BtnEgreso)
        self.BtnRespaldo = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnRespaldo.sizePolicy().hasHeightForWidth())
        self.BtnRespaldo.setSizePolicy(sizePolicy)
        self.BtnRespaldo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnRespaldo.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Respaldo.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnRespaldo.setIcon(icon4)
        self.BtnRespaldo.setIconSize(QtCore.QSize(30, 30))
        self.BtnRespaldo.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnRespaldo.setObjectName("BtnRespaldo")
        self.verticalLayout.addWidget(self.BtnRespaldo)
        self.LabelDatos = QtWidgets.QLabel(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelDatos.sizePolicy().hasHeightForWidth())
        self.LabelDatos.setSizePolicy(sizePolicy)
        self.LabelDatos.setMinimumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setMaximumSize(QtCore.QSize(250, 40))
        self.LabelDatos.setStyleSheet(
            "#LabelDatos {\n"
            "    font-weight: bold; /* Negrita */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "}\n"
            ""
        )
        self.LabelDatos.setObjectName("LabelDatos")
        self.verticalLayout.addWidget(self.LabelDatos)
        self.BtnProductos = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnProductos.sizePolicy().hasHeightForWidth())
        self.BtnProductos.setSizePolicy(sizePolicy)
        self.BtnProductos.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnProductos.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Productos.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnProductos.setIcon(icon5)
        self.BtnProductos.setIconSize(QtCore.QSize(30, 30))
        self.BtnProductos.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnProductos.setObjectName("BtnProductos")
        self.verticalLayout.addWidget(self.BtnProductos)
        self.BtnCrediFactura = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BtnCrediFactura.sizePolicy().hasHeightForWidth()
        )
        self.BtnCrediFactura.setSizePolicy(sizePolicy)
        self.BtnCrediFactura.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnCrediFactura.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/CrediFactura.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnCrediFactura.setIcon(icon6)
        self.BtnCrediFactura.setIconSize(QtCore.QSize(30, 30))
        self.BtnCrediFactura.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnCrediFactura.setObjectName("BtnCrediFactura")
        self.verticalLayout.addWidget(self.BtnCrediFactura)
        self.BtnFacturas = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnFacturas.sizePolicy().hasHeightForWidth())
        self.BtnFacturas.setSizePolicy(sizePolicy)
        self.BtnFacturas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnFacturas.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Facturas.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnFacturas.setIcon(icon7)
        self.BtnFacturas.setIconSize(QtCore.QSize(30, 30))
        self.BtnFacturas.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnFacturas.setObjectName("BtnFacturas")
        self.verticalLayout.addWidget(self.BtnFacturas)
        self.BtnReportes = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnReportes.sizePolicy().hasHeightForWidth())
        self.BtnReportes.setSizePolicy(sizePolicy)
        self.BtnReportes.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnReportes.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Reportes.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnReportes.setIcon(icon8)
        self.BtnReportes.setIconSize(QtCore.QSize(30, 30))
        self.BtnReportes.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnReportes.setObjectName("BtnReportes")
        self.verticalLayout.addWidget(self.BtnReportes)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            150,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        self.verticalLayout.addItem(spacerItem1)
        self.BtnControlUsuario = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BtnControlUsuario.sizePolicy().hasHeightForWidth()
        )
        self.BtnControlUsuario.setSizePolicy(sizePolicy)
        self.BtnControlUsuario.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnControlUsuario.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/Usuarios.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnControlUsuario.setIcon(icon9)
        self.BtnControlUsuario.setIconSize(QtCore.QSize(30, 30))
        self.BtnControlUsuario.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnControlUsuario.setObjectName("BtnControlUsuario")
        self.verticalLayout.addWidget(self.BtnControlUsuario)
        self.BtnUsuario = QtWidgets.QToolButton(parent=self.Navbar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnUsuario.sizePolicy().hasHeightForWidth())
        self.BtnUsuario.setSizePolicy(sizePolicy)
        self.BtnUsuario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BtnUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/perfil.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.BtnUsuario.setIcon(icon10)
        self.BtnUsuario.setIconSize(QtCore.QSize(60, 60))
        self.BtnUsuario.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.BtnUsuario.setObjectName("BtnUsuario")
        self.verticalLayout.addWidget(self.BtnUsuario)
        self.horizontalLayout_2.addWidget(self.Navbar)
        self.Contenido = QtWidgets.QWidget(parent=self.Contenedor)
        self.Contenido.setStyleSheet(
            "margin-left:10px;\n"
            "border-radius:15px;\n"
            "\n"
            "background-color: #f2f2f2; \n"
            "\n"
            ""
        )
        self.Contenido.setObjectName("Contenido")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Contenido)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.Contenido)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LabelReportes = QtWidgets.QLabel(parent=self.widget_2)
        self.LabelReportes.setStyleSheet(
            "#LabelReportes\n"
            " {\n"
            "    font-weight: bold; /* Negrita */\n"
            "    font-size: 34px; /* Tamaño de fuente */\n"
            "}\n"
            ""
        )
        self.LabelReportes.setObjectName("LabelReportes")
        self.horizontalLayout_3.addWidget(self.LabelReportes)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(350, 70))
        self.pushButton_3.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: red; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}"
        )
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(
                "d:\\SYSTOCK\\SYSTOCK\\DESARROLLO\\python\\programacion_ladynails\\Project_LadyNails\\app\\ui\\../../assets/iconos/pdf.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_3.setIcon(icon11)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(
            self.pushButton_3, 8, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_2.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(
            "\n" "    font-size: 28px; /* Tamaño de fuente */\n" ""
        )
        self.label.setObjectName("label")
        self.gridLayout.addWidget(
            self.label,
            0,
            0,
            1,
            1,
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop,
        )
        self.label_2 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(250, 50))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(
            self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(250, 50))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.calendarWidget.sizePolicy().hasHeightForWidth()
        )
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(
            self.calendarWidget,
            7,
            0,
            1,
            1,
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop,
        )
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet(
            "\n" "    font-size: 28px; /* Tamaño de fuente */\n" ""
        )
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(
            self.label_5, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(350, 70))
        self.pushButton_5.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: red; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}"
        )
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_3.addItem(spacerItem3, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_6.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(250, 50))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(350, 70))
        self.pushButton_8.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background-color: red; /* Fondo blanco */\n"
            "    border: none; /* Sin borde ni decoración inicial */\n"
            "    color:  white; /* Color del texto */\n"
            "    border-radius: 15px; /* Bordes circulares */\n"
            "    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
            "    height: 40px; /* Altura del botón */\n"
            "    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
            "    font-size: 18px; /* Tamaño de fuente */\n"
            "    margin-top:20px;\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
            "    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
            "}"
        )
        self.pushButton_8.setIcon(icon11)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_4.addWidget(
            self.pushButton_8, 6, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_6 = QtWidgets.QLabel(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet(
            "\n" "    font-size: 28px; /* Tamaño de fuente */\n" ""
        )
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(
            self.label_6, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_7.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 4, 0, 1, 1)
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.calendarWidget_2.sizePolicy().hasHeightForWidth()
        )
        self.calendarWidget_2.setSizePolicy(sizePolicy)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.gridLayout_4.addWidget(
            self.calendarWidget_2,
            5,
            0,
            1,
            1,
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter,
        )
        self.label_8 = QtWidgets.QLabel(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(250, 50))
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_4.addItem(spacerItem4, 7, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.gridLayout_2.addWidget(self.Contenedor, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LabelFuncionalidades.setText(_translate("Form", "Funcionalidades"))
        self.BtnVentas.setToolTip(
            _translate(
                "Form", '<html><head/><body><p align="center"><br/></p></body></html>'
            )
        )
        self.BtnVentas.setText(_translate("Form", "   Ventas"))
        self.BtnCaja.setText(_translate("Form", "   Caja"))
        self.BtnCredito.setText(_translate("Form", "   Credito"))
        self.BtnEgreso.setText(_translate("Form", "   Egreso"))
        self.BtnRespaldo.setText(_translate("Form", "   Respaldo"))
        self.LabelDatos.setText(_translate("Form", "Datos"))
        self.BtnProductos.setText(_translate("Form", "   Productos"))
        self.BtnCrediFactura.setText(_translate("Form", "   CrediFactura"))
        self.BtnFacturas.setText(_translate("Form", "   Factura"))
        self.BtnReportes.setText(_translate("Form", "   Reportes"))
        self.BtnControlUsuario.setText(_translate("Form", "   Control Usuarios"))
        self.BtnUsuario.setText(_translate("Form", "   Usuario"))
        self.LabelReportes.setText(_translate("Form", "Reportes"))
        self.pushButton_3.setText(_translate("Form", "   Generar PDF"))
        self.pushButton_2.setText(_translate("Form", "Diario / Intervalo"))
        self.label.setText(_translate("Form", "Reporte de Caja"))
        self.label_2.setText(_translate("Form", "Caja"))
        self.pushButton.setText(_translate("Form", "Ingreso / Egreso"))
        self.label_3.setText(_translate("Form", "Tiempo"))
        self.label_5.setText(_translate("Form", "Reporte de Productos"))
        self.pushButton_4.setText(
            _translate("Form", "Bajo Stock / Mas Vendidos / Inactivos")
        )
        self.pushButton_5.setText(_translate("Form", "   Generar PDF"))
        self.pushButton_6.setText(
            _translate("Form", "Comparacion /  Analisis Credito ")
        )
        self.label_7.setText(_translate("Form", "Ventas"))
        self.pushButton_8.setText(_translate("Form", "Exportar PDF"))
        self.label_6.setText(_translate("Form", "Analisis de Venta"))
        self.pushButton_7.setText(_translate("Form", "Dias / Intervalo de Dias"))
        self.label_8.setText(_translate("Form", "Tiempo"))
